kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: registry.cn-beijing.aliyunc s.com/ismewen/ismewen
      registry: registry.cn-beijing.aliyuncs.com
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    volumes:
      - name: dockercache
        path: /var/lib/docker
volumes:
- name: dockercache
  host:
    path: /tmp/docker/${DRONE_REPO}/${DRONE_BRANCH}